name: spring2
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mustache:
    suffix: .html
  jpa:
    hibernate:
#      ddl-auto: create # 매번 테이블을 생성한다.
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: warn
    jpabook.jpashop.study.springboot: trace